language: node_js
node_js:
  - 16.17.0
cache:
  directories:
    - node_modules
services:
  - mongodb
install:
  - npm ci
script:
  - npm test
before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
deploy:
  provider: heroku
  api_key:
    secure: GW3l/ebGdKBuxngwLn8zQANPM7HsO0qKy/BEipqZle+5aR4Zk+ZL02XPZGxe7MebuwtQ9bdnPewjfgs9KOtITMWW0cki1tl2bi4oy2lTw3oT8WcTSIqdmdSvI6jwQVOxgP3lSAV+JDBOtAg1g+/7IY+uPLkq7z8Xh7fQBdJcsyXRGAYrwdyWnK72sLZ88p84T5NAFAZiBJ9pO3Mgs8b44TFA7MzlaupeCbLgxLTlFPglVOgXwbEdoJxPV4Oowb4PpWSzYRJNH7bqDIKje+YAl0VVI8oyQm2vAuIiFEOpnrGYLclVnXanxzfFny0GMLgIl/rNiETsL/poAqFwy+lNd5l2loxTa4vqXwBMfwOLCcOrOuZo0YfmK1xuASUwepGXgj6ulX4fzzQxLKOMzWVi+pXN7OBzckskzItFp87adaim6v1IYLuqmhZ2bmHPVprmAsVnS8dbb1IwqmNKuMEIB2siSXitTuaRhrK8gWMPM7VznKFnVyIUZF6dVAO5pF9rd//SXFHewGNcBWQFyfp4m++svfyX5Irgox2jriKl+FFWbH+N4Wd0gOjE9dALY60eGV24L8LfRLb09Jp6jaUxTiGG/Yz/ZOVrgShTfkPeym+E99haOo0XroCwI0/YTZgV+UnSJMlxC1wuvE4RCLgqktKLFzaLdiYEAbvFm7G/zOw=
  app: cs3219-otot-taskb
  on:
    repo: hsiaotingluv/CS3219-OTOT-TaskB
    branch: main
